show-diffs: true
watch-files: true

gitignore: false
auto-commits: false

cache-prompts: true
chat-language: the same language of user's question, prefer English

user-input-color: "" # use default foreground color
