multiline: true
show-diffs: true
watch-files: true

gitignore: false
auto-commits: false

architect: true
cache-prompts: true
auto-accept-architect: false

model: opus
weak-model: deepseek
editor-model: sonnet
chat-language: >
  prefer English or Chinese for explanation, according to the language of
  user's question; always generate code or comments with English

user-input-color: "" # use default foreground color
