gui:
  border: 'single'
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
refresher:
  refreshInterval: 1
update:
  method: never
promptToReturnFromSubprocess: false
notARepository: 'skip'
keybinding:
  universal:
    gotoTop: 'g'
    gotoBottom: 'G'
  commits:
    renameCommit: 'i'
    renameCommitWithEditor: 'e'
    viewResetOptions: 'r'
    squashAboveCommits: 'S'
    amendToCommit: 'A'
  stash:
    popStash: 'o'
    renameStash: 'i'
