gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
    optionsTextColor:
      - white
    selectedLineBgColor:
      - white
      - bold
    selectedRangeBgColor:
      - white
      - bold
    unstagedChangesColor:
      - magenta
