# vim:ft=yaml:sw=2:sts=2:

repos:
- repo: local
  hooks:
    - id: sh-format
      name: Shell script format
      entry: shfmt -w
      language: system
      types: [shell]

    - id: sh-lint
      name: Shell script lint
      entry: shellcheck
      language: system
      types: [shell]
