#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Watch for sleep signal to check & set bg on awake from sleep

if ! command -v checkbg &>/dev/null; then
    echo "Error: checkbg not found"
    exit 1
fi

while true; do
    checkbg
    sleep 600
done
