#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Watch for sleep signal to check & set bg on awake from sleep

if ! command -v checkbg &>/dev/null; then
    echo "Error: checkbg not found"
    exit 1
fi

dbus-monitor --system "type='signal', \
        interface='org.freedesktop.login1.Manager', \
        member=PrepareForSleep" | while read x; do
    if [[ "$x" == *"boolean false"* ]]; then
        checkbg
    fi
done
