#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:
# Watch for sleep signal to check current time and set bg accordingly on awake from sleep

has_recent_conflict_bg() {
    timestamp_file="${XDG_STATE_HOME:-$HOME/.local/state}/setbg/timestamp"
    if [ ! -e "$timestamp_file" ]; then
        return 1
    fi

    prev_time=$(cat "$timestamp_file") # seconds since the epoch (1970-01-01 00:00 UTC)
    if [ -z "$prev_time" ] || [ $(($(date +%s) - prev_time)) -gt $((12 * 60 * 60)) ]; then
        return 1
    fi
}

dbus-monitor --system "type='signal', \
        interface='org.freedesktop.login1.Manager', \
        member=PrepareForSleep" | while read -r x; do
    case "$x" in
    *"boolean false"*)
        if ! has_recent_conflict_bg; then
            checkbg
        fi
        ;;
    esac
done
