#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

# Set bg to suggested bg

main() {
    cur_bg=$(getbg)
    target_bg=$(suggestbg)

    if [ "$cur_bg" != "$target_bg" ]; then
        setbg "$target_bg"
    fi
}

main "$@"
