#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Check sunrise/sunset and set desktop background accordingly

__has() {
    command -v "$1" >/dev/null 2>&1
}

if ! __has setbg; then
    echo "Error: setbg is not installed" >&2
    exit 1
fi

# If `sunwait` is installed, use it to determine if it's day or night
if __has sunwait; then
    setbg "$([[ "$(sunwait poll)" == DAY ]] && echo light || echo dark)"
else
    # Else use current time to determine if it's day or night
    current_hour=$(date +%H)
    setbg "$([[ "$current_hour" -gt 6 && "$current_hour" -lt 18 ]] &&
        echo light ||
        echo dark)"
fi
