#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Extract files from archive, wisely

# Check if a file/directory does not exist
checkne() {
    if [[ -e "$1" ]]; then
        echo "Error: '$1' already exists"
        return 1
    fi
    return 0
}

main() {
    if [[ ! -f "$1" ]]; then
        echo "'$1' is not a valid file"
        return 1
    fi

    # Get filename without extension
    local filename=$(basename "$1")
    local frootname="${filename%.*}"
    while [[ "$frootname" == *"."* ]]; do
        frootname="${frootname%.*}"
    done

    # Extract directly if the archive contains only one file/directory,
    # else we extract it into a separate directory
    case "$1" in
    *.tar.Z)
        if (($(tar tZf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar xZf "$1" -C "$frootname" || return 1
        else
            tar xZf "$1"
        fi
        ;;
    *.Z) uncompress "$1" ;;
    *.tar.bz2 | *.tbz2)
        if (($(tar tjf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar xjf "$1" -C "$frootname" || return 1
        else
            tar xjf "$1"
        fi
        ;;
    *.bz2) bunzip2 "$1" ;;
    *.tar.gz | *.tgz)
        if (($(tar tzf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar xzf "$1" -C "$frootname" || return 1
        else
            tar xzf "$1"
        fi
        ;;
    *.gz) checkne "$frootname" && gunzip -c "$1" >"$frootname" || return 1 ;;
    *.tar.xz | *.txz)
        if (($(tar tJf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar xJf "$1" -C "$frootname" || return 1
        else
            tar xJf "$1"
        fi
        ;;
    *.xz) unxz "$1" ;;
    *.tar.lzma)
        if (($(tar --lzma -tf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar --lzma -xf "$1" -C "$frootname" || return 1
        else
            tar --lzma -xf "$1"
        fi
        ;;
    *.lzma) unlzma "$1" ;;
    *.tar.zst | *.tzst)
        if (($(tar --zstd -tf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar --zstd -xf "$1" -C "$frootname" || return 1
        else
            tar --zstd -xf "$1"
        fi
        ;;
    *.zst) zstd -d "$1" ;;
    *.tar.lz4)
        if (($(tar --use-compress-program=lz4 -tf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar --use-compress-program=lz4 -xf "$1" -C "$frootname" || return 1
        else
            tar --use-compress-program=lz4 -xf "$1"
        fi
        ;;
    *.lz4) lz4 -d "$1" ;;
    *.rar)
        if unrar l "$1" | grep -q '^.*/$'; then
            checkne "$frootname" && mkdir "$frootname" &&
                unrar x "$1" "$frootname" || return 1
        else
            unrar x "$1"
        fi
        ;;
    *.tar)
        if (($(tar tf "$1" | wc -l) > 1)); then
            checkne "$frootname" && mkdir "$frootname" &&
                tar xf "$1" -C "$frootname" || return 1
        else
            tar xf "$1"
        fi
        ;;
    *.zip)
        if zipinfo -1 "$1" | grep -q '^.*/$'; then
            checkne "$frootname" && mkdir "$frootname" &&
                unzip "$1" -d "$frootname" || return 1
        else
            unzip "$1"
        fi
        ;;
    *.7z)
        if 7z l "$1" | grep -q '^.*/$'; then
            checkne "$frootname" && mkdir "$frootname" &&
                7z x "$1" -o"$frootname" || return 1
        else
            7z x "$1"
        fi
        ;;
    *) echo "'$1' cannot be extracted" ;;
    esac
}

main "$1"
