#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

VIM_COMMAND=$(command -v nvim || command -v vim)
ARGS="$*"

[[ -z "$ARGS" ]] &&
    $VIM_COMMAND +'Git' +'silent! only' ||
    $VIM_COMMAND +"exe escape('Git -p $ARGS', \"\\'\")" +'silent! only'
