#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

ARGS="$*"

if command -v nvim >/dev/null 2>&1; then
    VIM_COMMAND='nvim -E --headless'
else
    VIM_COMMAND='vim -E'
fi

if [ -z "$ARGS" ]; then
    $VIM_COMMAND +'GBrowse' +'qa!'
else
    $VIM_COMMAND +"exe escape('GBrowse $ARGS', \"\\'\")" +'qa!'
fi

echo
