#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :

VIM_COMMAND=$(command -v nvim 2>/dev/null || command -v vim || exit)
ARGS="$*"

if [ -z "$ARGS" ]; then
    $VIM_COMMAND +'Git' +'silent! only'
else
    $VIM_COMMAND +"exe escape('Git -p $ARGS', \"\\'\")" +'silent! only'
fi
