#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :

VIM_COMMAND=$(command -v nvim >/dev/null 2>&1 && echo 'nvim -E --headless' || 'vim -E')
ARGS="$*"

[ -z "$ARGS" ] &&
    $VIM_COMMAND +'GBrowse' +'qa!' ||
    $VIM_COMMAND +"exe escape('GBrowse $ARGS', \"\\'\")" +'qa!'

echo
