#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

if [ -z "$1" ]; then
    pwd
    exit 0
fi

case "$1" in
.) pwd ;;
..) cd .. && pwd ;;
./*) printf '%s/%s\n' "$(pwd)" "${1#./}" ;;
../*) printf '%s/%s\n' "$(cd .. && pwd)" "${1#../}" ;;
*) printf '%s/%s\n' "$(cd "$(dirname "$1")" && pwd)" "$(basename "$1")" ;;
esac
