#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

# Convert hex color code to rgb format, receives
# multiple hex color codes from stdin, one per line
hex2rgb() {
    hex=$(cat)
    for hex_code in $hex; do
        hex_code=${hex_code#\#}

        r=${hex_code%????}
        g=${hex_code#??}
        g=${g%??}
        b=${hex_code#????}

        r=$(printf '%d' "0x$r")
        g=$(printf '%d' "0x$g")
        b=$(printf '%d' "0x$b")

        printf '%d,%d,%d\n' "$r" "$g" "$b"
    done
}

hex2rgb "$@"
