#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

md2html() {
    pandoc \
        --katex \
        --standalone \
        --embed-resources \
        -f markdown-implicit_figures \
        --css ~/.pandoc/css/paper.css \
        -t html \
        "$1" \
        -o "${1%.md}.html"
}

main() {
    rc=0

    for file in "$@"; do
        oldpwd=$PWD

        # Pictures in markdown cannot be fetched if we are not in the same
        # directory
        cd "$(dirname "$(realpath "$file")")" || return

        if ! md2html "$(basename "$file")"; then
            echo "md2html: error: pandoc failed to convert '$file'" >&2
            cd "$oldpwd" || return
            rc=1
        fi

        cd "$oldpwd" || return
    done

    return "$rc"
}

main "$@"
