#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

md2html2pdf() {
    pandoc \
        --katex \
        --pdf-engine="$PDF_ENGINE" \
        -V margin-top=10 \
        -V margin-bottom=10 \
        -V margin-left=8 \
        -V margin-right=8 \
        --css ~/.pandoc/css/paper.css \
        -f markdown-implicit_figures \
        -t pdf \
        "$1" \
        -o "${1%.md}.pdf"
}

main() {
    PDF_ENGINE="wkhtmltopdf"
    while getopts "lxmhp" opt; do
        case $opt in
        l) PDF_ENGINE="lualatex" ;;
        x) PDF_ENGINE="xelatex" ;;
        m) PDF_ENGINE="latexmk" ;;
        h) PDF_ENGINE="wkhtmltopdf" ;;
        p) PDF_ENGINE="pdflatex" ;;
        ?)
            printf "Usage: %s [-l|-x|-m|-h|-p] files\n" "$(basename "$0")" >&2
            return 1
            ;;
        esac
    done
    shift $((OPTIND - 1))

    [ $# -eq 0 ] && {
        echo "Error: no input files" >&2
        return 1
    }

    rc=0

    for file in "$@"; do
        oldpwd=$PWD

        # Pictures in markdown cannot be fetched if we are not in the same
        # directory
        cd "$(dirname "$(realpath "$file")")" || return

        if ! md2html2pdf "$(basename "$file")"; then
            echo "md2html2pdf: error: pandoc failed to convert '$file'" >&2
            cd "$oldpwd" || return
            rc=1
        fi

        cd "$oldpwd" || return
    done

    return "$rc"
}

main "$@"
