#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:

md2tex() {
    pandoc \
        --standalone \
        -f markdown-implicit_figures \
        -t latex \
        "$1" \
        -o "${1%.md}.tex"
}

main() {
    if [ $# -eq 0 ]; then
        echo "Error: no input files" >&2
        printf "Usage: %s files...\n" "$(basename "$0")" >&2
        return 1
    fi

    rc=0

    for file in "$@"; do
        oldpwd=$PWD

        # Pictures in markdown cannot be fetched if we are not in the same
        # directory
        cd "$(dirname "$(realpath "$file")")" || return

        if ! md2tex "$(basename "$file")"; then
            rc=$?
            echo "md2tex: error: pandoc failed to convert '$file' with exit code $rc" >&2
            cd "$oldpwd" || return
            rc=1
        fi

        cd "$oldpwd" || return
    done

    return "$rc"
}

main "$@"
