#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

md2tex() {
    pandoc \
        --standalone \
        -f markdown-implicit_figures \
        -t latex \
        "$1" \
        -o "${1%.md}.tex"
}

main() {
    for file in "$@"; do
        # Pictures in markdown cannot be fetched if
        # we are not in the same directory.
        cd "$(dirname "$(readlink -f "$file")")" >/dev/null 2>&1 || exit 1
        md2tex "$(basename "$file")" || {
            echo >&2 "md2tex: error: pandoc failed to convert '$file'"
            exit 1
        }
        cd - >/dev/null 2>&1
    done
}

main "$@"
