#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Make a backup for a file or directory

print_help() {
    script_name=$(basename "$0")
    cat <<EOF
${script_name} - make backup
Usage: ${script_name} <file>

Options:
  -h, --help    Show this help message
EOF
}

# Remove trailing slashes from path
clean_path() {
    while [ "${1%/}" != "$1" ]; do
        set -- "${1%/}"
    done
    printf '%s\n' "$1"
}

main() {
    case "$1" in
    '' | -h | --help)
        print_help
        return 0
        ;;
    esac

    src="$1"
    bak="$(clean_path "$1").bak"

    if [ ! -e "$src" ]; then
        echo "'$src' does not exist" >&2
        return 1
    fi

    if [ -e "$bak" ]; then
        echo "'$bak' already exists" >&2
        return 1
    fi

    cp -LR "$src" "$bak"
}

main "$@"
