#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :
# Make a backup for a file or directory

print_help() {
    local script_name=$(basename "$0")
    cat <<EOF
${script_name} - make backup
Usage: ${script_name} <file>

Options:
  -h, --help    Show this help message
EOF
}

main() {
    if [[ -z "$1" ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
        print_help
        return 0
    fi

    local src="$1"
    shopt -s extglob && local bak="${1%%+(/)}.bak"

    if [[ ! -e "$src" ]]; then
        echo "'$src' does not exist" 2>&1
        return 1
    fi

    if [[ -e "$bak" ]]; then
        echo "'$bak' already exists"
        return 1
    fi

    cp -Lr "$src" "$bak"
}

main "$@"
