#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

has() {
    command -v "$1" >/dev/null 2>&1
}

if ! has nvim || ! has find; then
    return 1
fi

RUNTIME_DIR="${XDG_RUNTIME_DIR:-${TMP:-/run/user/$(id -u)}}"
APPNAME="${NVIM_APPNAME:-nvim}"

find "$RUNTIME_DIR" -type s -name "$APPNAME.*.0" 2>/dev/null
