#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

RUNTIME_DIR="${XDG_RUNTIME_DIR:-${TMPDIR:-${TMP:-/run/user/$(id -u)}}}"
APPNAME="${NVIM_APPNAME:-nvim}"

has() {
    command -v "$1" >/dev/null 2>&1
}

if has fd; then
    fd -a --base-directory "$RUNTIME_DIR" -t s -g "$APPNAME.*.0" 2>/dev/null
    exit
fi

if has find; then
    find "$RUNTIME_DIR" -type s -name "$APPNAME.*.0" 2>/dev/null
    exit
fi

exit 1
