#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

__has() {
    command -v "$1" >/dev/null 2>&1
}

qdbus_cmd=$(__has qdbus && echo qdbus ||
    __has qdbus6 && echo qdbus6)

"$qdbus_cmd" org.kde.ksmserver /KSMServer saveCurrentSession
