#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :

# Find available qdbus command
if has qdbus; then
    qdbus_cmd="qdbus"
elif has qdbus6; then
    qdbus_cmd="qdbus6"
else
    echo "Error: neither qdbus nor qdbus6 found" >&2
    exit 1
fi

# Save current KDE Plasma session
"$qdbus_cmd" org.kde.ksmserver /KSMServer saveCurrentSession
