#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

__has() {
    command -v "$1" >/dev/null 2>&1
}

main() {
    # $1: name of the service
    # $2: method name
    # $3, $4, ...: method arguments
    local qdbus_cmd=$(__has qdbus && echo qdbus ||
        { __has qdbus6 && echo qdbus6; })
    if [[ -z "$qdbus_cmd" ]]; then
        echo "qdbus not found" >&2
        exit 1
    fi
    if [[ -z "$1" || -z "$2" ]]; then
        echo "Usage: $(basename $0) <service name> <method name> [method arguments]" >&2
        exit 1
    fi
    for service in $("$qdbus_cmd" | grep -iP "$1"); do
        for obj in $("$qdbus_cmd" "$service"); do
            local methods=$("$qdbus_cmd" "$service" "$obj")
            if [[ "$methods" =~ "$2" ]]; then
                "$qdbus_cmd" "$service" "$obj" "$2" "${@:3}"
            fi
        done
    done
}

main "$@"
