#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:
# Fetch files from <src> to <dest> periodically

main() {
    if ! has rsync; then
        echo 'rsync not found' >&2
        return 1
    fi

    src="$1"
    dst="$2"
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "Usage: $(basename "$0") <src> <dst>"
        return 1
    fi

    while true; do
        rsync -auzvP "$src" "$dst" && sleep 1 || return
    done
}

main "$@"
