#!/usr/bin/env sh
# vim:ft=sh:ts=4:sw=4:sts=4:et:
# Automatically push files from <src> to <dest> on local file change

push() {
    src="$1"
    dst="$2"
    rsync -auzvP --filter=":- $src/.gitignore" "$src" "$dst"
}

main() {
    if ! has rsync || ! has inotifywait; then
        echo 'rsync or inotifywait not found'
        return 1
    fi

    src="$1"
    dst="$2"
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "Usage: $(basename "$0") <src> <dst>"
        return 1
    fi

    echo "Initial push from $src to $dst..."
    push "$src" "$dst"
    while inotifywait -r -e modify,create,delete,move "$src" >/dev/null 2>&1; do
        echo "Changes detected, pushing $src to $dst..."
        push "$src" "$dst" || return
    done
}

main "$@"
