#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:
# Check sunrise/sunset and echo suggested background accordingly

# If `sunwait` is not installed, use current time to determine if it's day or night
if ! has sunwait; then
    current_hour=$(date +%H)
    current_hour="${current_hour#0}"
    [ "$current_hour" -gt 6 ] && [ "$current_hour" -lt 18 ] &&
        echo light ||
        echo dark
    exit
fi

# Use `sunwait` to determine if it's day or night
#
# shellcheck disable=SC2046 # we want to split result from `whereami` of the
# form 'latitude longitude', e.g. '55.6013N 83.7034W'
[ "$(sunwait poll $(whereami))" = "DAY" ] &&
    echo light ||
    echo dark
