#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

main() {
    # Try attach to existing unattached session, or create a new one
    # if none exists.
    if (tmux ls 2>/dev/null | grep -vq attached) && [[ "$PWD" == "$HOME" ]]; then
        tmux at
    else
        tmux
    fi
}

main
