#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

if ! command -v tmux >/dev/null 2>&1 || [[ -n "$TMUX" ]]; then
    exit 1
fi

# Try attach to existing unattached session, or create a new one
# if none exists.
if (tmux ls 2>/dev/null | grep -vq attached) && [[ "$PWD" == "$HOME" ]]; then
    tmux at
else
    tmux
fi
