#!/usr/bin/env sh
# vim:ft=sh:et:ts=4:sw=4:sts=4:
# Get current location in the format of 'latitude longitude'

LOC_URL=http://ipinfo.io/loc

if has curl; then
    coords=$(curl -s "$LOC_URL")
elif has wget; then
    coords=$(wget -qO- "$LOC_URL")
else
    # shellcheck disable=SC2016
    echo '`curl` or `wget` not found, cannot get location' >&2
    exit 1
fi

if [ -z "$coords" ] || ! (echo "$coords" | grep -Eq '^([+-]?[0-9]+\.[0-9]+,?){2}$'); then
    echo "Failed to get location from $LOC_URL: $coords" >&2
    exit 1
fi

latitude=${coords%,*}
longitude=${coords#*,}

# Convert latitude and longitude format from [+-]0.0000 to
# 0.0000[NS] (latitude) or 0.0000[EW] (longitude)
case "$latitude" in
-*) latitude="${latitude#-}S" ;;
*) latitude="${latitude}N" ;;
esac

case "$longitude" in
-*) longitude="${longitude#-}W" ;;
*) longitude="${longitude}E" ;;
esac

echo "$latitude" "$longitude"
