[colors]
ansi = [
    '#2f353e',
    '#e87c69',
    '#a4bd84',
    '#e6bb86',
    '#708296',
    '#caafeb',
    '#79ada7',
    '#e5e5eb',
]
brights = [
    '#e5e5eb',
    '#e87c69',
    '#a4bd84',
    '#e6bb86',
    '#708296',
    '#caafeb',
    '#79ada7',
    '#8f9fbc',
]
foreground = '#bebec3'
background = '#2f353e'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#2f353e'
selection_bg = '#404954'
selection_fg = '#bebec3'

[colors.indexed]

[metadata]
name = 'Cockatoo Dark'
author = 'Bekaboo'
