[colors]
ansi = [
    '#0d0c0c',
    '#e4948e',
    '#aaba9b',
    '#ffde91',
    '#abc4d0',
    '#c2b2c3',
    '#b5cecc',
    '#d4d3c7',
]
brights = [
    '#393836',
    '#ff8896',
    '#a7c9a7',
    '#ffc56d',
    '#9fd4ea',
    '#a39ac9',
    '#9ac8bf',
    '#e5e9e5',
]

foreground    = '#d4d3c7'
background    = '#181616'
cursor_fg     = '#181616'
cursor_bg     = '#d4d3c7'
cursor_border = '#1b1b1b'
selection_fg  = '#181616'
selection_bg  = '#d4d3c7'

[colors.indexed]

[metadata]
name = 'Macro Dark'
author = 'Bekaboo'
