[colors]
ansi = [
    '#181819',
    '#fc5d7c',
    '#9ed072',
    '#e7c664',
    '#76cce0',
    '#b39df3',
    '#85d3f2',
    '#e2e2e3',
]
brights = [
    '#7f8490',
    '#fc5d7c',
    '#9ed072',
    '#e7c664',
    '#76cce0',
    '#b39df3',
    '#85d3f2',
    '#e2e2e3',
]
foreground = '#e2e2e3'
background = '#2c2e34'
cursor_bg = '#e2e2e3'
cursor_border = '#e2e2e3'
cursor_fg = '#2c2e34'
selection_bg = '#3b3e48'
selection_fg = '#e2e2e3'

[colors.indexed]

[metadata]
name = 'Sonokai Dark'
author = 'Bekaboo'
