[colors]
ansi = [
    '#e7e7e7',
    '#d44e69',
    '#72ac38',
    '#be9b44',
    '#77bcd8',
    '#a793e3',
    '#77bcd8',
    '#171718',
]
brights = [
    '#7e8490',
    '#d44e69',
    '#72ac38',
    '#be9b44',
    '#77bcd8',
    '#a793e3',
    '#77bcd8',
    '#171718',
]
foreground = '#181819'
background = '#f3f3f3'
cursor_bg = '#181819'
cursor_border = '#181819'
cursor_fg = '#f3f3f3'
selection_bg = '#d1d4d4'
selection_fg = '#181819'

[colors.indexed]

[metadata]
name = 'Sonokai Light'
author = 'Bekaboo'
