# Everforest light theme
[colors.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#b8bea5"
yellow = "#dfa000"

[colors.cursor]
cursor = "#495b64"

[colors.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#b8bea5"
yellow = "#dfa000"

[colors.primary]
background = "#fdf6e3"
foreground = "#5c6a72"
