# Onedark dark theme
[colors.bright]
black   = "#5c6370"
red     = "#e86671"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.cursor]
cursor = "#fafafa"

[colors.normal]
black   = "#181a1f"
red     = "#e86671"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"
