# Sonokai light theme
[colors.bright]
black = "#7e8490"
blue = "#77bcd8"
cyan = "#77bcd8"
green = "#72ac38"
magenta = "#a793e3"
red = "#d44e69"
white = "#171718"
yellow = "#be9b44"

[colors.cursor]
cursor = "#181819"

[colors.normal]
black = "#e3e7e7"
blue = "#77bcd8"
cyan = "#77bcd8"
green = "#72ac38"
magenta = "#a793e3"
red = "#d44e69"
white = "#171718"
yellow = "#be9b44"

[colors.primary]
background = "#ecf0f0"
foreground = "#181819"
