[general]
import = [
    "~/.config/alacritty/themes/macro-dark.toml",
    "~/.config/alacritty/themes/dark.toml",
    "~/.config/alacritty/theme.toml",
    "$XDG_CONFIG_HOME/.config/alacritty/themes/macro-dark.toml",
    "$XDG_CONFIG_HOME/.config/alacritty/themes/dark.toml",
    "$XDG_CONFIG_HOME/.config/alacritty/theme.toml",
]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = "alacritty"

[font]
size = 12

[font.normal]
family = "Iosevka NF"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "B"
mode = "~Search"
mods = "Command"

[[mouse.bindings]]
action = "ReceiveChar"
mouse = "Right"

[scrolling]
history = 0

[window]
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 112
lines = 24

[window.padding]
x = 8
y = 8
