[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = 'alacritty'

[font]
size = 12

[font.normal]
family = 'Iosevka NF'

[scrolling]
history = 0

[window]
dynamic_padding = true
opacity = 1
option_as_alt = 'Both'

[window.dimensions]
columns = 112
lines = 24

[window.padding]
x = 8
y = 8
