[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[env]
TERM = 'alacritty'

[font]
size = 12

[font.normal]
family = 'Iosevka NF'

[scrolling]
history = 0

[window]
dynamic_padding = true
opacity = 1
option_as_alt = 'Both'

[window.dimensions]
columns = 112
lines = 24

[window.padding]
x = 8
y = 8

[keyboard]
bindings = [
    # Fix Ctrl-6 and Ctrl-5 keymap (used in neovim & tmux) on macOS
    # https://github.com/alacritty/alacritty/issues/1108
    #
    # To get hex keycode for a key: in a supported terminal, e.g. Kitty, open
    # neovim, press Ctrl-v + <key>, then put cursor over the char inserted and
    # press `ga`
    { key = 'Key6', mods = 'Control', chars = "\u001e" },
    { key = 'Key5', mods = 'Control', chars = "\u001d" }
]
