#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

connect() {
    if [ "$1" == 'client' ]; then
        ssh -p 2222 client@localhost
    elif [ "$1" == 'server' ]; then
        ssh -p 3333 server@localhost
    else
        echo "Argument must be either 'client' or 'server'"
    fi
}

main() {
    # If no argument is given, print usage and exit
    if [ -z "$1" ]; then
        echo "Usage: $0 [client|server]"
        exit 1
    fi

    connect "$1"
}

main "$@"
