#!/usr/bin/env sh
# vim: ft=sh ts=4 sw=4 sts=4 et :

cd ~

export GDK_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct
export XCURSOR_SIZE=24
export XCURSOR_THEME=breeze_cursors
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

exec Hyprland
