#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

NVIM_MANPAGER=1 nvim +'Man!' +'normal! Mzz' \
    +'silent! set ls=0 ch=1 so=999 nonu nornu scl=no stc= stl=' \
    +'silent! nnoremap d <C-d>' \
    +'silent! nnoremap u <C-u>' "$@"
