#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

main() {
    # $1: name of the app
    # $2: profile name
    if [[ -z "$(command -v qdbus 2>/dev/null)" || \
            -z "$(command -v kwriteconfig5 2>/dev/null)" ]]; then
        echo "qdbus or kwriteconfig5 not found" >&2
        exit 1
    fi
    if [[ -z "$1" || -z "$2" ]]; then
        echo "Usage: dbus-set-app-profile <app name> <profile name>" >&2
        exit 1
    fi
    kwriteconfig5 --file "${XDG_CONFIG_HOME:-$HOME/.config}/${1}rc" \
        --group 'Desktop Entry' \
        --key DefaultProfile "$2.profile"
    for service in $(qdbus | grep -iP "$1"); do
        for session in $(qdbus "$service"); do
            local methods=$(qdbus "$service" "$session")
            if [[ "$methods" =~ setProfile ]]; then
                qdbus "$service" "$session" setProfile "$2"
            fi
        done
    done
}

main "$@"
