#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

main() {
    # $1: name of the app
    # $2: 'light' or 'dark'
    if [[ -z "$(command -v kreadconfig5 2>/dev/null)" ]]; then
        echo "kreadconfig5 not found" >&2
        return 1
    fi
    if [[ -z "$1" || -z "$2" ]]; then
        echo "Usage: plasma-set-app-colorscheme <app name> <light|dark>" >&2
        return 1
    fi
    local rc="${XDG_CONFIG_HOME:-$HOME/.config}/${1}rc"
    local current_profile=$(kreadconfig5 --file "$rc" \
        --group "Desktop Entry" --key "DefaultProfile")
    local current_profile_name=${current_profile%\.profile}
    local new_profile_name=$(echo "$current_profile_name" | sed \
        "s/Dark\|Light/${2^}/" | sed "s/dark\|light/$2/")
    plasma-set-app-profile "$1" "$new_profile_name"
}

main "$@"
