#!/usr/bin/env bash
# vim: ft=sh ts=4 sw=4 sts=4 et :

build() {
    case "$1" in
        *.c)
            gcc "$1" -o "$2";;
        *.cpp)
            g++ "$1" -o "$2";;
    esac
}

exec() {
    "$1"
}

main() {
    FILE=$(full_path "$1")
    RUN_FILE=$(echo "$FILE" | sed -E 's/\.(c|cpp)$/.run/')
    if [[ "$FILE" == "$RUN_FILE" ]]; then
        >&2 echo "run: error: file name cannot be the same as the run file name"
        exit 1
    fi
    build "$FILE" "$RUN_FILE"
    if [[ ! -f "$RUN_FILE" ]]; then
        >&2 echo "run: error: cannot remove run file because it does not exist"
        exit 1
    fi
    exec "$RUN_FILE"
    rm "$RUN_FILE"
}

main "$1"
