# vim:ft=yaml:sw=2:sts=2:

repos:
- repo: local
  hooks:
    - id: lua-format
      name: Lua format
      entry: stylua
      language: system
      types: [lua]

    - id: lua-lint
      name: Lua lint
      entry: luacheck
      language: system
      types: [lua]
